/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BingeWatch: typeof import('./src/components/BingeWatch.vue')['default']
    ChoiceCom: typeof import('./src/components/ChoiceCom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTour: typeof import('element-plus/es')['ElTour']
    FlurBox: typeof import('./src/components/FlurBox.vue')['default']
    ItemCom: typeof import('./src/components/ItemCom.vue')['default']
    LoginCom: typeof import('./src/components/LoginCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCom: typeof import('./src/components/SelectCom.vue')['default']
    SortCom: typeof import('./src/components/SortCom.vue')['default']
  }
}
